server:
  port: 9081

spring:
  application:
    name: CONSUMER-SERVICE

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@eureka-primary:1111/eureka/,http://admin:admin@eureka-secondary:1112/eureka/,http://admin:admin@eureka-tertiary:1113/eureka/

logging:
  config: classpath:logback.xml




