server:
  port: 8081
  context-path: /one

spring:
  application:
    name: PROVIDER-SERVICE-ONE
  http:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB

eureka:
#  instance:
#    appname: PROVIDER-SERVICE-ONE-1
  client:
    service-url:
      defaultZone: http://admin:admin@eureka-primary:1111/eureka/,http://admin:admin@eureka-secondary:1112/eureka/,http://admin:admin@eureka-tertiary:1113/eureka/


logging:
  config: classpath:logback.xml


